version: '3.8'
services:
  mongo:
    image: mongo:7
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: chattyapp-backend

  cache:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - cache:/data

  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - mongo
      - cache
    environment:
      - DATABASE_URL=mongodb://mongo:27017/chattyapp-backend
      - REDIS_HOST=cache
      - REDIS_PORT=6379

volumes:
  mongo_data:
    driver: local
  cache:
    driver: local